project:
  type: book
  output-dir: docs

book:
  title: "Introdução aos modelos lineares dinâmicos"
  author: "James D Santos"
  date: "12/08/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - estacionaria.qmd
    - sinal.qmd
    - modelo_linear.qmd
    - mld.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
