project:
  type: book
  output-dir: docs

book:
  title: "Introdução aos modelos lineares dinâmicos"
  author: "James D Santos"
  date: "28/09/2023"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - sinal.qmd
    - acf.qmd
    - ferramentas.qmd
    - mld.qmd
    - polinomial.qmd
    - sazonal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
