# O modelo linear dinâmico

## O modelo linear dinâmico
Seja $y_1,\ldots,t$ uma série temporal. Seja $D_j={y_1,\ldots,y_j}$. Dizemos que $y_t$ é um modelo linear dinâmico se

$$\begin{align}
y_t|\boldsymbol{\theta}_t,D_{t-1}&\sim\hbox{Normal}(\boldsymbol{F}_t'\boldsymbol{\theta}_t,V_t)\\
\boldsymbol{\theta}_t|\boldsymbol{\theta}_{t-1},D_{t-1}&\sim\hbox{Normal}(\boldsymbol{G}_t\boldsymbol{\theta}_{t-1},\boldsymbol{W}_t)
\end{align}$$

A expressão acima, os $\theta$'s são denominados estados. Para a completa especificação do modelo, devemos informar valores iniciais $m_0$ e $C_0$ que representam nossa opinião sobre os estados antes do tempo $1$:

$$\theta_0\sim\ N(m_0,C_0)$$ Escolhas diferentes para $\boldsymbol{F}_t$ e $\boldsymbol{G}_t$ permitem acomodar sinais diferentes.

Pode-se mostrar que $y_{t+h}|D_t$ tem distribuição normal. Como $t+h$ é um tempo não observado, essa é a distribuição para previsões. Neste caso, a função de previsão para o horizonte $h$ é

$$f_t(h)=E(Y_{t+h}|D_{t})$$
onde $E(.)$ sempre deve ser lido como **média**.

O pacote para lidar com modelos lineares dinâmicos é o `dlm`. A função abaixo é utilizada para estimar as variâncias desconhecidas do modelo e deve sempre ser colocada no *environment* do `R`:

```{r}
require(dlm)

modFim <- function(y,mod){
  ffbs <- dlmGibbsDIG(y, mod = mod, n.sample = 5000,
                    a.y=1,b.y=100,a.theta=1,b.theta=100,
                    save.states = FALSE, thin = 0)

v_sim  <- sample(ffbs$dV[-(1:2500)],2500,T)

q <- dim(ffbs$dW)[2]
w_sim <- NULL
for(j in 1:q){
 w_sim <- c(w_sim, mean(sample(ffbs$dW[,j][-(1:2500)],2500,T)))
}
# declarando as variâncias na quádrupla
mod$V <- mean(v_sim)
mod$W <- diag( w_sim)
return(mod)
}
```

Também pode-se mostrar que $\theta_{t-h}|D_t$ tem distribuição normal. Como se trata da distribuição dos estados após verificar toda a série temporal, esta é a distribuição para a suavização.

