# Modelo linear dinâmico polinomial

O modelo dinâmico polinomial de ordem $p$ é dado pela quádrupla $\{\boldsymbol{F},\boldsymbol{G},.,.\}$ onde $\boldsymbol{F}'=(1,\boldsymbol{0}'_{p-1})$ - e $\boldsymbol{0}_{p-1}$ é um vetor coluna de comprimento $p-1$ composto somente por zeros - e $\boldsymbol{G}$ é uma matriz $p\times p$, triangular superior com todos os elementos não nulos iguais a 1. 

Observe que a matriz $\boldsymbol{G}$ pode ser escrita como $\textbf{I}_p+\boldsymbol{N}$ onde $\boldsymbol{N}_{i,j}=1$ se $i<j$ e $\boldsymbol{N}_{i,j}=0$. Então, para $h$ natural, teremos que

$$\boldsymbol{G}^h = (\textbf{I}_p+\boldsymbol{N})^h=\sum_{i=0}^h {h\choose i}\boldsymbol{N}^i.$$

Contudo, a matriz $\boldsymbol{N}$ é nilipotente, com $\boldsymbol{N}^p=\textbf{0}_{p\times p}$. Deste modo, A matrix 

$$\boldsymbol{G}^h = (\textbf{I}_p+\boldsymbol{N})^h=\sum_{i=0}^p {h\choose i}\boldsymbol{N}^i.$$

Portanto, a função de previsão deste modelo é dada por
	$$f_t(h)=\boldsymbol{F}'\boldsymbol{G}^h\boldsymbol{m}_t =\boldsymbol{F}'\sum_{i=0}^{p-1}{h\choose i}\boldsymbol{N}^i\boldsymbol{m}_t=\sum_{i=0}^{p-1}{h\choose i}\boldsymbol{F}'\boldsymbol{N}^i\boldsymbol{m}_t$$
que	sempre será um polinômio de grau $p-1$.


Os MLD polinomiais são uma alternativa atrativa para modelos com tendência ou nível aleatório.


## O modelo linear dinâmico polinomial de primeira ordem
	
	O modelo linear de primeira ordem é dado por $\{1,1,.,.\}$ e possui função de previsão dada por
	
	$$f_t(h)=F'G^hm_t = m_t.$$
	
	Este modelo é interessante para analisar séries com oscilação de nível, mas é útil apenas para previsões um passo a frente. 
	
	Para $t$ suficientemente grande, esse modelo converge para o \textbf{Método de Holt}

## O modelo linear dinâmico polinomial de segunda ordem

	Para o modelo linear dinâmico polinomial de ordem 2, temos 
	
	$$\boldsymbol{F}'=(1,0)$$
	e
	 $$\boldsymbol{G}=\left(\begin{array}{cc} 1 & 1 \\ 0 & 1 \end{array}\right)$$
	
	Neste caso
	
		 $$\boldsymbol{G}^h=\left(\begin{array}{cc} 1 & h \\ 0 & 1 \end{array}\right)$$

e

$$\begin{align*}
		f_t(h)&=(1,0)\left(\begin{array}{cc}1&h \\0&1 \end{array}\right)\boldsymbol{m}_t= m_{1,t}+h m_{2,t},
	\end{align*}$$
	
	Note que $m_{1,t}$ representa o nível da série no tempo $t$, enquanto que $m_{2,t}$ representa a inclinação da tendência (crescimento/decrescimento).  
	
	
Para $t$ suficientemente grande, esse modelo converge para o método de Crescimento linear de Holt.




