# Variâncias desconhecidas: lidando com $V_t$ e $W_t$

## O modelo linear dinâmico com variância observacional constante

Seja $y_t$ uma série temporal univariada e considere o caso no qual $V_t$ é desconhecida, mas constante, ou seja $V_t=V$ para todo $t$. Como uma das componentes da quádrupla é desconhecida, o modelo não é mais um MLD. Contudo, ainda podemos definir um MLD condicionado à $V$. Vamos reparametrizar esse modelo com as seguintes componentes:


* Equações das Observações condicionadas a $V$:

$$\boldsymbol{y}_t|\boldsymbol{\theta}_t,V\sim \sim\hbox{Normal}(\boldsymbol{F}_t'\boldsymbol{\theta}_t,V)$$

	
* Equações dos Estados condicionadas a $\boldsymbol{V}$:

$$\boldsymbol{\theta}_t|\boldsymbol{\theta}_{t-1},V\sim\hbox{Normal}(\boldsymbol{G}_t\boldsymbol{\theta}_{t},V\boldsymbol{W}_t^\star)$$

* Informação inicial: considerando a precisão $\phi=1/V$,

$$\begin{align*}
		\boldsymbol{\theta}_0|D_0,V&\sim\hbox{Normal}(\boldsymbol{m}_0,V\boldsymbol{C}_0^\star)\\
		\phi|D_0 &\sim\hbox{Gama}\left(\frac{n_0}{2},\frac{n_0S_0}{2}\right)
	\end{align*}$$
	
Na definição acima, a matriz de covariância da evolução agora é descrita como $V\boldsymbol{W}_t$ e o mesmo acontece com a matriz de covariância de $\theta_0$. 
Note que não existem prejuízos nas definições. Por exemplo, fazendo $\boldsymbol{W}_t=V\boldsymbol{W}_t^\star$ nós voltamos ao modelo de evolução usual.

Os hiper parâmetros da precisão são $n_0/2$ e $n_0s_0/2$. Teremos
$$E[\phi|y_0]=\frac{1}{s_0}$$
onde $S_0$ faz (aproximadamente) o papel de informação a priori sobre a média de $V$.
Além disso,
$$Var[\phi|y_0]=\frac{2}{n_0s_0^2}$$
e $n_0$ regula nossa crença em $\phi$: quanto menor for $n_0$ mais difusa será a distribuição de $\phi$. Valores típicos para uma priori pouco informativa são $n_0=0,01$ e $s_0=0,01$


<div class='alert alert-success'>
**Proposição.** O MLD condicioando à $V_t=V$ para todo $t$, possui as seguintes alterações no filtro de Kalman:

1. Priori para o tempo $t$:    
	$$\boldsymbol{\theta}_t|D_{t-1},V\sim\hbox{Normal}(\boldsymbol{a}_t,V\boldsymbol{R}_t^\star),$$
	onde 
$$\begin{align}
\boldsymbol{a}_t&=\boldsymbol{G}_t\boldsymbol{m}_{t-1}\\
	\boldsymbol{R}_t^\star&=\boldsymbol{W}_t^\star+\boldsymbol{G}_t\boldsymbol{C}_{t-1}^\star\boldsymbol{G}_t'.\end{align}$$
	
2. Previsão 1 passo à frente:

$$y_t|D_{t-1},V\sim\hbox{Normal}(f_t,VQ_t^\star)$$
onde 
$$\begin{align}
f_t&=\boldsymbol{F}_t\boldsymbol{a}_t\\ Q_t^\star&= 1+\boldsymbol{F}_t'\boldsymbol{R}_t^\star\boldsymbol{F}_t
\end{align}$$

3. Posteriori para o tempo $t$: $\boldsymbol{\theta}_t|D_t,V\sim\hbox{Normal}(\boldsymbol{m}_t,V\boldsymbol{C}_t^\star)$,
		onde 
		
$$\begin{align*}
			\boldsymbol{A}_t &= \boldsymbol{R}_t^\star\boldsymbol{F}_t/Q_t^\star\\
			\boldsymbol{m}_t & =\boldsymbol{a}_t+\boldsymbol{A}_t(y_t-f_t)\\
			\boldsymbol{C}_t^\star&=\boldsymbol{R}_t^\star-\boldsymbol{A}_t\boldsymbol{A}_t'Q_t^\star
		\end{align*}$$
</div>

Observe que a posteriori para $\phi$ no tempo $t$ pode ser facilmente atualizada via conjugação, como mostra o teorema abaixo

::: {#thm- .alert .alert-success}
**Posteriori para $\phi$ no tempo $t$.** Para cada $t>0$,
	
$$\phi|D_{t}\sim\hbox{Gama}\left(\frac{n_t}{2},\frac{n_ts_t}{2}\right)$$
onde
	
$$\begin{align}
	n_t&=n_{t-1}+1\\
	s_t&=\frac{n_{t-1}}{n_t}s_{t-1}+\frac{(y_t-f_t)^2}{n_tQ_t^\star}\end{align}$$
:::

**Demonstração.**

Sabemos que $\phi|D_0\sim\hbox{Gama}(n_0/2,n_0s_0/2)$ . Suponha que $\phi|D_{t-1}\sim\hbox{Gama}(n_{t-1}/2,n_{t-1}s_{t-1}/2)$. Então
	
$$\begin{align*}
		f(\phi|D_{t})&\propto f(D_t,\phi)=f(y_t|\phi,D_{t-1})f(\phi|D_{t-1})\\
		&\propto \phi^{1/2}\exp\left\{-\frac{\phi}{2Q_t^\star}(y_t-f_t)^2\right\}\times \phi^{n_{t-1}/2-1}\exp\left\{-\frac{n_{t-1}s_{t-1}}{2}\phi\right\}
		\\
		&\propto \phi^{\frac{n_{t-1}+1}{2}-1}\exp\left\{-\frac{\phi}{2}\left[\frac{(y_t-f_t)^2}{Q_t^\star}+n_{t-1}s_{t-1}\right]\right\}
	\end{align*}$$
	
A demonstração termina fazendo $n_t=n_{t-1}+1$ e fazendo
$$\frac{(y_t-f_t)^2}{Q_t^\star}+n_{t-1}s_{t-1}=n_t\left[\frac{(y_t-f_t)^2}{n_tQ_t^\star}+\frac{n_{t-1}}{n_t}s_{t-1}\right].$$
Portanto, $\phi|D_{t}\sim\hbox{Gama}(n_t/2,n_ts_t/2)$. $\blacksquare$

Observe pela Proposição 1 que todas as componentes do filtro de Kalman condicionadas à  $V$ possuem distribuição normal. Sem perda de generalidade, considere que uma componente em particular, $\boldsymbol{x}$ tem distribuição Normal$(\boldsymbol{\mu},V\Sigma)$. Como $V^{-1}=\phi\sim\hbox{Gama}(n/2,ns/2)$, teremos

$$\boldsymbol{x}=\int_0^\infty \phi^{\frac{n-1}{2}}e^{-\frac{\phi}{2}\left[ns +(\boldsymbol{x}-\boldsymbol{\mu})'\Sigma^{-1} (\boldsymbol{x}-\boldsymbol{\mu})\right]}d\phi\propto \left\{1+\frac{1}{n}(\boldsymbol{x}-\boldsymbol{\mu})'(s\Sigma)^{-1} (\boldsymbol{x}-\boldsymbol{\mu})\right\}^{-\frac{n-1}{2}}$$
ou seja, $\boldsymbol{x}\sim t_{n}(\boldsymbol{\mu}, s^2\Sigma)$. Podemos então enunciar a atualização incondicionada à $V$.

::: {#thm- .alert .alert-success}
**Atualização do MLD incondicionado à $V$:** Para uma série temporal univariada $y_t$, seja $\{\boldsymbol{F}_t,\boldsymbol{G}_t,V,V\boldsymbol{W}_t\}$ um MLD com $V^{-1}=\phi|D_0\sim\hbox{Gama}(n_0/2, n_0s_0/2)$. Então

1. Priori para o tempo $t$: $\boldsymbol{\theta}_t|D_{t-1}\sim t_{n_{t-1}}(\boldsymbol{a}_t,s_{t-1}^2\boldsymbol{R}_t),$$
	onde 
	$$\begin{align}
	\boldsymbol{a}_t&=\boldsymbol{G}_t\boldsymbol{m}_{t-1}\\
	\boldsymbol{R}_t&=s_{t-1}\boldsymbol{R}_{t}^\star\end{align}$$.
2. Previsão um passo à frente: 	$y_t|D_{t-1}\sim t_{n_{t-1}}(f_t,Q_t),$
	onde 
	$$\begin{align}
	f_t&= \boldsymbol{F}_t'\boldsymbol{a}_t\\
	Q_t&= s_{t-1}Q_t^\star
	\end{align}$$
	$Q_t=S_{t-1}Q_{t}^\star$.
	
3. Posterioris para o tempo $t$: $\boldsymbol{\theta}_t|D_{t}\sim t_{n_{t}}(\boldsymbol{m}_t,\boldsymbol{C}_t)$ e $\phi|D_t\sim\hbox{Gama}(n_t/2, n_ts_t/2)$, onde 

$$\begin{align}
\boldsymbol{A}_t&=\boldsymbol{R}_t\boldsymbol{F}_tQ_t^{-1}\\
\boldsymbol{m}_t&= \boldsymbol{a}_t + \boldsymbol{A}_t( y_t - f_t)\\
\boldsymbol{C}_t&=s_t\boldsymbol{C}_t^\star=s_t[\boldsymbol{R}_t^\star-\boldsymbol{A}_tQ_t^{\star}\boldsymbol{A}_t']=\frac{s_t}{s_{t-1}}[\boldsymbol{R}_t-\boldsymbol{A}_tQ_t\boldsymbol{A}_t']
\end{align}$$
:::

Observe que resultados análogos podem ser obtidos para a suavização e previsão, como mostram os seguintes teoremas.

::: {#thm- .alert .alert-success}
**Suavização.** Seja $y_t$ um modelo linear dinâmico com quádrupla $\{\boldsymbol{F}_t,\boldsymbol{G}_t,V,V\boldsymbol{W}_t\}$, com $V^{-1}=\phi|D_0\sim\hbox{Gama}(n_0/2,n_0s_0/2)$. Então para o modelo condicionado à $V$, teremos que, para qualquer $k=0,\ldots,t$:

$$\boldsymbol{\theta}_{t-k}|V,D_t\sim\hbox{Normal}(\boldsymbol{a}_t(-k),V\boldsymbol{R}_t^\star(-k)),$$
onde
$$\begin{align}
\boldsymbol{B}_t&=\boldsymbol{C_t}^\star\boldsymbol{G}_{t+1}'\boldsymbol{R}_{t+1}^{\star'}\\
\boldsymbol{a}_t(-k)&=\boldsymbol{m}_{t-k}+\boldsymbol{B}_{t-k}[\boldsymbol{a}_t(-k+1)-\boldsymbol{a}_{t-k+1}]\\
\boldsymbol{R}_t^{\star}(-k)&=\boldsymbol{C}_{t-k}^{\star}-\boldsymbol{B}_{t-k}[\boldsymbol{R}_{t-k+1}^{\star}-\boldsymbol{R}_t^{\star}(-k+1)]\boldsymbol{B_{t-k}}'
\end{align}$$
enquanto que o modelo incondicional à $V$ é dado por

$$\boldsymbol{\theta}_{t-k}|D_t\sim\hbox{t}_{n_t}(\boldsymbol{a}_t(-k),\boldsymbol{R}_t(-k)),$$
onde
$$\begin{align}
\boldsymbol{R}_t(-k)&=s_t \boldsymbol{R}_t^{\star}(-k)
\end{align}$$
:::

::: {#thm- .alert .alert-success}
**Previsão.** Seja $y_t$ um modelo linear dinâmico com quádrupla $\{\boldsymbol{F}_t,\boldsymbol{G}_t,V,V\boldsymbol{W}_t\}$, com $V^{-1}=\phi|D_0\sim\hbox{Gama}(n_0/2,n_0s_0/2)$. Então para o modelo condicionado à $V$, teremos que, para qualquer $h>0$:

1. $\boldsymbol{\theta}_{t+h}|V,D_t\sim\hbox{Normal}(\boldsymbol{a}_t(h),V\boldsymbol{R}_t^\star(h))$
2. $y_{t+h}|V,D_t\sim\hbox{Normal}(f_t(h),VQ_t^\star(h))$
onde
$$\begin{align}
\boldsymbol{a}_t(h)&=\boldsymbol{G}_{t+h}\boldsymbol{a}_{t}(h-1)\\
f_t(h)&=\boldsymbol{F}'_{t+h}\boldsymbol{a}_{t}(h)\\
\boldsymbol{R}_t^{\star}(h)&=\boldsymbol{G}_{t+h}\boldsymbol{R}_{t}^\star(h-1)\boldsymbol{G}_{t+h}'+\boldsymbol{W}_{t-k}\\
Q_t^\star(h)&=\boldsymbol{F}_{t+h}'\boldsymbol{R}_{t}^\star(h)\boldsymbol{F}_{t+h}+1
\end{align}$$
enquanto que o modelo incondicional à $V$ é dado por

$$y_{t+h}|D_t\sim\hbox{t}_{n_t}({f}_t(h),Q_t(h)),$$
onde
$$\begin{align}
Q_t(h)&=s_t Q_t^{\star}(h).
\end{align}$$
:::

## Fatores de desconto

Nessa seção lidaremos com a variância $\boldsymbol{W}_t$ desconhecida. Por motivação, considere o modelo $\{1,1,V_t,W_t\}$. Neste caso, teremos 
$$\begin{align*}
	R_t &= Var(\theta_t|D_{t-1})\\
	&= E(Var(\theta_t|\theta_{t-1})) + Var(E(\theta_t|\theta_{t-1}))\\
	&= W_t + C_{t-1}
\end{align*}$$


Assim, $W_t$ representa o aumento da incerteza sobre $\theta_{t}$ entre a informação no tempo $t-1$ e a priori no tempo $t$. Como $W_t\geq0$, existe $\alpha_t\geq1$ tal que
$$R_t=\alpha_t C_{t-1}.$$

Assuma que $\alpha_t=\alpha$ é constante para todo $t$.  Podemos então determinar a variação da informação sobre $\theta_{t}$ entre a a posteriori no tempo $t-1$ e priori no tempo $t$ a partir da razão
$$\frac{C_{t-1}}{R_t}=\frac{1}{\alpha}:=\delta.$$
A quantidade $\delta\in(0,1]$ é denominada \textbf{fator de descontos}.

De modo geral, um fator de descontos é interpretado como a porcentagem (da variação) da informação passada entre $\theta_{t-1}|D_{t-1}$ para $\theta_{t}|D_{t-1}$. Neste caso, teremos que
$$R_t = \frac{C_{t-1}}{\delta}$$
ou ainda,
$$W_t = C_{t-1}\left(\frac{1}{\delta}-1\right)$$

Pela última relação, podemos ver que manter $\delta\approx 1$ faz com que $W_t\approx 0$, o que é razoável em termos práticos quando o sinal é pouco ruidoso. 
Podemos notar ainda que, no filtro de Kalman,

$$A_t= R_tQ_t^{-1}=\left[\frac{C_{t-1}}{\delta}\right]\frac{1}{V_t+C_{t-1}/\delta}=\frac{C_{t-1}}{\delta V_t+C_{t-1}},$$

e, como  
$$\begin{align*}
	m_{t+1}&=a_{t}+A_t(y_t-f_t)
\end{align*}$$
logo, fatores de descontos próximos de 0 eliminam o peso de $y_t$ para compor a posteriori. 

No caso geral, para quádrupla $\{\boldsymbol{F}_t,\boldsymbol{G}_t,\boldsymbol{V}_t,\boldsymbol{W}_t\}$, temos 
$$\boldsymbol{R}_t = \boldsymbol{W}_t +\boldsymbol{G}_t\boldsymbol{C}_{t-1}\boldsymbol{G}_t'.$$
Podemos utilizar a estratégia de descontos de modo similar ao que foi feito anteriormente:
$$\boldsymbol{R}_t = \frac{1}{\delta}\boldsymbol{G}_t\boldsymbol{C}_{t-1}\boldsymbol{G}_t'.$$  

Neste caso, 
$$\boldsymbol{W}_t = \left(\frac{1}{\delta}-1\right)\boldsymbol{G}_t\boldsymbol{C}_{t-1}\boldsymbol{G}_t'.$$  

Algumas regras práticas:

* Estaremos interessados em utilizar fatores de descontos altos, tipicamente dentro do intervalo $[0,8;1]$, para garantir que a informação proveniente dos dados está sendo considerada na composição da posteriori.

* Em geral, utilizamos um fator de descontos constante para toda a série.

* Fatores de descontos baixos serão desejados quando houver uma mudança súbita na série - neste caso, ter uma variância inflada e tomar o último valor de $y_t$ como estimativa para o nível é uma boa estratégia para a adaptação rápida do sistema.



